server:
  port: 8082
  context-path: /hystrix_product

spring:
  application:
    name: hystrix_product
  profiles:
    active: dev
  messages:
    basename: i18n/messages,i18n/errors
  jackson:
    default-property-inclusion: non_null

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 1
    minIdle: 1
    maxActive: 5
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
  mapper-locations: classpath*:mybatis/mapper/**/*.xml
  config-locations: classpath*:mybatis/config.xml
  type-handlers-package: com.fan.mybatis.handler.AESEncryptHandler
logging:
  path: ./logs/hystrix_product
fan:
  bootstrap:
    microkernel: false

